# Generated by Django 4.0.1 on 2022-01-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image_upload',
        ),
    ]
