# Generated by Django 4.0.1 on 2022-02-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=256, unique=True)),
                ('sub', models.CharField(blank=True, max_length=256)),
                ('time', models.DateTimeField(blank=True, max_length=6)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='image_upload',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='rollno',
            field=models.CharField(default='1234567891234567', max_length=16),
        ),
    ]
