# Generated by Django 4.0.1 on 2022-02-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0002_meetinginfo_remove_userprofileinfo_image_upload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingInfo',
        ),
    ]
