# Generated by Django 4.0.1 on 2022-01-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0002_remove_userprofileinfo_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='roll_no',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
