# Generated by Django 4.0.1 on 2022-02-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0003_alter_meetinginfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginfo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
