# Generated by Django 4.0.1 on 2022-02-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0003_delete_meetinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=256, unique=True)),
                ('sub', models.CharField(blank=True, max_length=256)),
                ('time', models.DateTimeField(blank=True, max_length=6)),
            ],
        ),
    ]
