# Generated by Django 4.0.1 on 2022-01-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0003_remove_userprofileinfo_user_userprofileinfo_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
