# Generated by Django 4.0.1 on 2022-01-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLP', '0007_alter_userprofileinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='name',
        ),
    ]
